# FORMAT_DATE, FORMAT_DATETIME, FORMAT_TIMESTAMP

SELECT
  CURRENT_DATE AS exe1,
  FORMAT_DATE("%b %d", CURRENT_DATE) AS exe2,
  FORMAT_DATE("%Y-%m", CURRENT_DATE) AS exe3,
  FORMAT_DATE("%Y-%m, %A", CURRENT_DATE) AS exe4,
  FORMAT_DATE("%D", CURRENT_DATE) AS exe5;

select 
  CURRENT_DATETIME('America/Recife') AS exe6,
  FORMAT_DATETIME("%T", CURRENT_DATETIME('America/Recife')) AS exe7;
